apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "shoe"
  namespace: ms
  labels:
    app:  "shoe"
spec:
  selector:
    matchLabels:
      app: "shoe"
  template:
    metadata:
      labels:
        app:  "shoe"
    spec:
      containers:
      - name:  "shoe"
        image:  zackz001/mssvc02-shoe:v1
        ports:
        - containerPort:  1002
          name:  "shoe"

---
apiVersion: v1
kind: Service
metadata:
  name: "shoe"
  namespace: ms
spec:
  selector:
    app: "shoe"
  type: ClusterIP
  ports:
  - name: "shoe"
    port: 1002
    targetPort: 1002