version: '3'
services:
  vpronginx:
    image: zackz001/redo20-e4-web:v2
    ports:
      - "80:80"

  vproapp:
    image: zackz001/redo20-e4-app:v2 
    ports:
      - "8080:8080"

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vprodb:
    image: zackz001/redo20-e4-db:v2
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

volumes:
  vprodbdata: {}
