apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: k8s-microsvc
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: ClusterIP
