# I want to create a service by using yaml for bellow deployment :
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: k8s-microsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: zackz001/emartapp-client:v1
          ports:
            - containerPort: 4200
