apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: k8s-microsvc
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 4200
      targetPort: client-port
  type: ClusterIP
