# I want to create a service by using yaml for bellow deployment :
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  namespace: k8s-microsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
#      initContainers:
#        - name: wait-for-api
#          image: busybox:latest
#          command: ['sh', '-c', 'until nc -z api-service 5000; do echo "Waiting for api service..."; sleep 2; done']
#        - name: wait-for-webapi
#          image: busybox:latest
#          command: ['sh', '-c', 'until nc -zv webapi-service 9000; do echo "Waiting for webapi service..."; sleep 5; done']
      containers:
        - name: client
          image: zackz001/emartapp-client:v1
          ports:
            - containerPort: 4200
