apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: k8s-microsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      initContainers:
        - name: wait-for-webapi
          image: busybox:1.34
          command: ['sh', '-c', 'until nc -zv webapi-service 9000; do echo "Waiting for webapi service..."; sleep 5; done']
      initContainers:
        - name: wait-for-api
          image: busybox:1.34
          command: ['sh', '-c', 'until nc -zv api-service 5000; do echo "Waiting for api service..."; sleep 5; done']
        - name: client
          image: zackz001/emartapp-client:v1
          ports:
            - containerPort: 4200
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4200
