apiVersion: v1
kind: Service
metadata:
  name: emongo-service
  namespace: k8s-microsvc
spec:
  selector:
    app: emongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
