apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: efk
  labels:
    app: kibana-logging
spec:
  ports:
  - port: 5601
  type: NodePort
  selector:
    app: kibana-logging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: efk
  labels:
    app: kibana-logging
spec:
  selector:
    matchLabels:
      app: kibana-logging
  template:
    metadata:
      labels:
        app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana:7.9.1
        resources:
          limits:
            memory: 800Mi
          requests:
            memory: 700Mi
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch-logging:9200
        ports:
        - containerPort: 5601
