apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-microsvc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginx-port
  type: NodePort
