# I want to create a service by using yaml for bellow deployment :
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ngnix-pv
  namespace: k8s-microsvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/nginx/data/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: k8s-microsvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: k8s-microsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      initContainers:
#        - name: wait-for-client
#          image: busybox:latest
#          command: ['sh', '-c', 'until nc -zv client-service 4200; do echo "Waiting for client service..."; sleep 5; done']
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: nginx-port
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/
              subPath: nginx.conf

      volumes:
        - name: nginx-config-volume
          persistentVolumeClaim:
            claimName: nginx-pvc

