# I want to create a service by using yaml for bellow deployment :

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: k8s-microsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      initContainers:
#        - name: wait-for-client
#          image: busybox:latest
#          command: ['sh', '-c', 'until nc -zv client-service 4200; do echo "Waiting for client service..."; sleep 5; done']
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: nginx-port
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config

