# I want to create a service by using yaml for bellow deployment :
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: k8s-microsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: zackz001/emartapp-api:v1
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
