# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
#---
# How do we want it implemented
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: local-storage
#spec:
#  storageClassName: mylocalstorage
#  capacity:
#    storage: 20Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/some new/directory/structure/"
#    type: DirectoryOrCreate
