apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: k8s-microsvc
spec:
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 9000
      targetPort: webapi-port
  type: ClusterIP
